### ISSUE TITLE
report of undefined

### ISSUE THREAD

**Issue by danielhanzs** [BoLaMN/loopback-datatype-objectid#1]
Hi there,

I dont know what went wrong, but after the 1.0.1 version when I want to start the application it got an error that the reports is undefined which comes from the arg.reports.

Could you please check it, I reverted back to 1.0.0.

Also thanks for this little plugin helps a lot with mongo.

have a nice day!

**Comment by BoLaMN** [comment]
Hey, 

I just published 1.0.3 which hopefully fixes the issue, did some tests locally and it seemed to work are you able to give it a test when you next get the chance to upgrade

cheers!

**Comment by danielhanzs** [comment]
Hi,

I upgraded and heres is the message:

> set NODE_ENV=development&& nodemon .

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node .`
D:\laragon\www\apps\gepaukciok\node_modules\loopback\lib\application.js:62
  if (this._remotes) {
          ^

TypeError: Cannot read property '_remotes' of undefined
    at app.remotes (D:\laragon\www\apps\gepaukciok\node_modules\loopback\lib\application.js:62:11)
    at module.exports (D:\laragon\www\apps\gepaukciok\node_modules\loopback-datatype-objectid\index.js:30:3)
    at Object.<anonymous> (D:\laragon\www\apps\gepaukciok\server\server.js:18:38)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
[nodemon] app crashed - waiting for file changes before starting...

This is with loopback 3.x

Thanks

**Comment by BoLaMN** [comment]
my bad, 

i pulled the code out of my mongo custom connector and forgot the app context

newer version published again

cheers

**Comment by danielhanzs** [comment]
Thanks looking good and working, have a nice day!
